name: SOURCE_EVENT
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to send to downstream repository'
        required: true

permissions: write-all

jobs:
  dispatch-custom-event:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.DOWNSTREAM_REPO_DISPATCH_TOKEN }}
    steps:
    - name: Trigger downstream repository_dispatch
      run: |
        gh api \
          --method POST\
          repos/SauVans/githubActions2/dispatches \
          -f event_type='githubActions-release-published' \
          -F "client_payload[release_version]=${{ github.event.inputs.release_version }}"
  

