name: SOURCE_EVENT
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to send to downstream repository'
        required: true
      release_version_for_action:
        description: 'Release version to send to downstream repository with action (can be different from release_version to test different versions)'
        required: true

permissions: write-all

jobs:
  dispatch-custom-event:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.DOWNSTREAM_REPO_DISPATCH_TOKEN }}
    steps:
    - name: Trigger downstream repository_dispatch
      run: |
        ORT_RELEASE_BRANCH="release/${{ github.event.inputs.release_version }}"
        gh api \
          --method POST\
          repos/SauVans/githubActions2/dispatches \
          -f event_type='githubActions-release-published' \
          -F "client_payload[ort_release_branch]=${ORT_RELEASE_BRANCH}"

  dispatch-custom-event-with-action:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.DOWNSTREAM_REPO_DISPATCH_TOKEN }}
    steps:
    - name: checkout repository
      uses: actions/checkout@v4


    - name: Trigger downstream repository_dispatch with action
      uses: ./.github/actions/gh-repo-dispatch
      with:
        app: githubActions
        version: ${{ github.event.inputs.release_version_for_action }}
        repository: SauVans/githubActions2
        token: ${{ secrets.DOWNSTREAM_REPO_DISPATCH_TOKEN }}
  

